package com.aryavarta.identity.exception;

public enum TenantProvisioningErrorCode {

    TENANT_CODE_ALREADY_EXISTS,
    TENANT_NAME_ALREADY_EXISTS,
    PLAN_NOT_FOUND,
    PLAN_INACTIVE,
    LEGAL_ENTITY_CODE_ALREADY_EXISTS,
    ADMIN_USERNAME_ALREADY_EXISTS,
    ADMIN_EMAIL_ALREADY_EXISTS,
    TENANT_ADMIN_ROLE_NOT_FOUND,
    PROVISIONING_FAILED
}