package com.aryavarta.core.hr.entity.enums;

public enum EmploymentEventType {
    JOINED,
    PROBATION_STARTED,
    PROBATION_COMPLETED,
    PROMOTION,
    TRANSFER,
    POSITION_CHANGED,
    ORG_UNIT_CHANGED,
    LOCATION_CHANGED,
    MANAGER_CHANGED,
    GRADE_CHANGED,
    SALARY_CHANGED,
    EMPLOYMENT_TYPE_CHANGED,
    STATUS_CHANGED,
    LEAVE_OF_ABSENCE,
    RETURNED_FROM_LEAVE,
    SUSPENDED,
    REACTIVATED,
    TERMINATED,
    RETIRED
}
