package com.aryavarta.identity.record.auth;

public enum AuthErrorCode {

    INVALID_CREDENTIALS,
    INVALID_REFRESH_TOKEN,
    REFRESH_TOKEN_EXPIRED,
    SESSION_REVOKED,
    TENANT_MISMATCH,
    USER_NOT_FOUND,
    USER_INACTIVE,
    ACCOUNT_LOCKED,
    MFA_REQUIRED,
    INVALID_MFA_CODE,
    AUTHENTICATION_REQUIRED,
    ACCESS_DENIED,
    VALIDATION_ERROR
}